# Generated by Django 2.2 on 2020-12-28 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='description',
            field=models.TextField(max_length=1000, null=True, verbose_name='个性签名'),
        ),
    ]
